import random
import string

LOCAL_RANDOM_PLACEHOLDERS = ["[File]",  "[Directory]",  "[Executable]", "[TarFile]", "[ZipFile]"]
RANDOM_PLACEHOLDERS = ["[GlobalFile]", "[GlobalDirectory]", "[GlobalExecutable]", "[Interface]", "[Username]", "[Groupname]"]
RANDOM_STR_PLACEHOLDERS = {"[Password]": ["password", "pass", "1234", "admin"],
       "[String]": ["matrix", "region", "rusted", "monkey", "browse", "uproot", "outlet",
                    "accept", "immune", "forked", "banana", "bob", "bumblebee", "ubuntu", "[RandomString]"],
       "[NewFile]": ["file", "file.1", "file.2", "file.txt", "newfile", "newfile1", "[RandomString]"],
       "[NewDirectory]": ["dir", "dir1", "docs", "newdir", "newdir1", "tmpdir", "[BadTarget]"],
       "[NewExecutable]": ["exec", "newexec", "exec.sh", "esec.py", "[BadTarget].sh", "[BadTarget].py", "[BadTarget].c"],
       "[UtilPath]": ["/usr/bin/ls",
                      "/usr/bin/sh",
                      "/usr/bin/pwd",
                      "/usr/bin/w",
                      "/usr/bin/ls",
                      "/usr/bin/ps",
                      "/var/log/auth.log",
                      "/var/log/syslog"],
       "[BadTarget]": ["[String]", "[RandomString]"],
                           "[spaceOpt]": [  # for options that don't need a space (but could have one)
                               " ",
                               ""
                           ],
       "[BadDirectory]": [
           "[BadTarget]",
           "/[BadTarget]",
           "[BadTarget]/",
           "[Directory]/[BadTarget]",
           "[GlobalDirectory]/[BadTarget]",
           "/[BadTarget][GlobalDirectory]"
       ],
       "[AnyDir]": ["[Directory]", "[GlobalDirectory]"],
        "[AnyTarget]": [
                "[AnyDir]",
                "[FileTarget]",
                "[gzipTarget]",
                "[Executable]"
            ],
       "[AnyTargets]": [
           "[AnyTarget]",
           "[AnyTarget] [AnyTarget]",
           "[AnyTarget] [AnyTarget] [AnyTarget]"
       ],
        "[gzipTarget]": [
                "[File]",
                "[ZipFile]"
            ],
       "[StringOpt]": [
           "",
           "[RandomString]"
       ],
       "[FileTarget]": [
           "[File]",
           "[File]",
           "[File]",
           "[File]",
           "[File]",
           "[File]",
           "[GlobalFile]",
           "[GlobalFile]",
           "[GlobalFile]",
           "[BadTarget]"
       ],
       "[DirectoryTarget]": [
           "[Directory]",
           "[Directory]",
           "[Directory]",
           "[Directory]",
           "[Directory]",
           "[Directory]",
           "[GlobalDirectory]",
           "[GlobalDirectory]",
           "[GlobalDirectory]",
           "[BadDirectory]"
       ],
        "[CpSrc]": [
            "[FileTarget]",
            "[DirectoryTarget]"
            ],
       "[Files]": [
           "[FileTarget]",
           "[FileTarget] [FileTarget]",
           "[FileTarget] [FileTarget] [FileTarget]"],
       "[Directories]": [
           "[DirectoryTarget]",
           "[DirectoryTarget] [DirectoryTarget]",
           "[DirectoryTarget] [DirectoryTarget] [DirectoryTarget]"],
       "[NewFiles]": [
           "[NewFile]",
            "[NewFile] [NewFile]",
            "[NewFile] [NewFile] [NewFile]"],
       "[IP]": [
           "172.16.0.[IPNumber]",
           "172.16.[IPNumber].[IPNumber]",
           "127.0.0.1",
           "172.16.0.1"
           "[WebServer]"
       ],
        "[Domain]": [
                "google.com"
        ],
       "[DNSIP]": [
           "10.100.1.1",
            "8.8.8.8",
            "8.8.4.4"
            "1.1.1.1"
        ],
       "[HTTPAgent]": [
                "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0",
                "Mozilla/5.0 (Macintosh; Intel Mac OS X x.y; rv:42.0) Gecko/20100101 Firefox/42.0",
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36",
                "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.106 Safari/537.36 OPR/38.0.2220.41",
                "Opera/9.80 (Macintosh; Intel Mac OS X; U; en) Presto/2.2.15 Version/10.00",
                "Opera/9.60 (Windows NT 6.0; U; en) Presto/2.1.1",
                "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.59",
                "Mozilla/5.0 (iPhone; CPU iPhone OS 13_5_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Mobile/15E148 Safari/604.1",
                "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)",
                "Mozilla/5.0 (compatible; YandexAccessibilityBot/3.0; +http://yandex.com/bots)",
                "curl/[SmallNumber].[MediumNumber].[SmallNumber]",
                "wget/[SmallNumber].[MediumNumber].[SmallNumber]",
                "PostmanRuntime/[SmallNumber].[MediumNumber].[SmallNumber]"
       ],
        "[Service]": [
                "acpid",
                "avahi-daemon",
                "binfmt-support",
                "cron",
                "cups",
                "grub-common",
                "hwclock.sh",
                "plymouth",
                "plymouth-log",
                "procps",
                "rsync",
                "rsyslog",
                "saned",
                "ssh",
                "udev",
                "unattended-upgrades",
                "x11-common"
            ],
        "[HTTPMethod]": [
                "GET",
                "POST",
                "PUSH",
                "PUT",
                "OPTIONS",
                "HEAD"
            ],
        "[TCPCongAlgs]": [
            "tahoe",
            "reno",
            "cubic"
          ],
        "[IPcRealms]": [
            "cosmos",
            "inr.ac",
            "inr.ruhep",
            "freenet",
            "radio-msu",
            "russia",
            "internet",
            "[SmallNumber]"
          ],

        "[QuotePattern]": ["\"[Pattern]\""],
        "[FilePattern]":[
            "*[Extension]",
            "*[Extension].[SmallNumber]",
            "*[SmallNumber]",
            "*.[SmallNumber]",
            "[Character]*[Extension]"
            "[0-9]*[String][Extension]",
            "[0-9]*[String][0-9]*",
            "[a-zA-Z]*[Extension]",
            "[a-zA-Z0-9]*[Extension]",
            "[a-zA-Z0-9]*.[a-zA-Z0-9]*[Extension]",
            "[Directory]/[FilePattern]",

                           ],
        "[Pattern]": [
            "*\\.zip",
            "*\\.sh",
            "*\\.py",
            "*\\.tar\\.*",
            "*\\.[a-z].gz"
            ".*\\.zip",
            ".*\\.sh",
            ".*\\.py",
            ".*\\.tar\\.*",
            ".*\\.[a-z].gz"
            "^./.*\\.zip",
            "^./.*\\.sh",
            "^./.*\\.py",
            "^./.*\\.txt",
            "^./.*\\.tar\\.*",
            "^/etc/*"
            "^/etc/.*"
            "[0-9]+",
            ".*",
            "^.*[0-9]$",
            "^.*.[0-9]$",
            ".*/bin/?.*",
            "root",
            "[_rwx]{3}",
            ",[0-9]+",
            "^\\./.+/",
            ".*\\d"
            ],
        "[Path]": [
                "[GlobalDirectory]",
                "[GlobalFile]"
            ],
        "[HTTPCodeList]": [
                "[HTTPCode]",
                "[HTTPCode],[HTTPCode]",
                "[HTTPCode],[HTTPCode],[HTTPCode]"
            ],
        "[Variable]": [
                "SHELL",
                "SESSION_MANAGER",
                "QT_ACCESSIBILITY",
                "COLORTERM",
                "XDG_CONFIG_DIRS",
                "XDG_MENU_PREFIX",
                "GNOME_DESKTOP_SESSION_ID",
                "MANDATORY_PATH",
                "GNOME_SHELL_SESSION_MODE",
                "SSH_AUTH_SOCK",
                "XMODIFIERS",
                "DESKTOP_SESSION",
                "SSH_AGENT_PID",
                "GTK_MODULES",
                "PWD",
                "LOGNAME",
                "XDG_SESSION_DESKTOP",
                "XDG_SESSION_TYPE",
                "GPG_AGENT_INFO",
                "XAUTHORITY",
                "WINDOWPATH",
                "HOME",
                "USERNAME",
                "IM_CONFIG_PHASE",
                "LANG",
                "LS_COLORS",
                "XDG_CURRENT_DESKTOP",
                "VTE_VERSION",
                "GNOME_TERMINAL_SCREEN",
                "INVOCATION_ID",
                "MANAGERPID",
                "LESSCLOSE",
                "XDG_SESSION_CLASS",
                "TERM",
                "DEFAULTS_PATH",
                "LESSOPEN",
                "LIBVIRT_DEFAULT_URI",
                "USER",
                "GNOME_TERMINAL_SERVICE",
                "DISPLAY",
                "SHLVL",
                "QT_IM_MODULE",
                "XDG_RUNTIME_DIR",
                "JOURNAL_STREAM",
                "XDG_DATA_DIRS",
                "GDMSESSION",
                "DBUS_SESSION_BUS_ADDRESS",
                "_",
                "[String]"
            ],
           "[Variables]":[
               "[Variable]",
               "[Variable] [Variable]",
               "[Variable] [Variable] [Variable]"
           ],

            "[MACAddr]": [
                    "[HexChar][HexChar]:[HexChar][HexChar]:[HexChar][HexChar]:[HexChar][HexChar]:[HexChar][HexChar]:[HexChar][HexChar]"
                ],

            "[IPMask]": [
                "255.255.255.255",
                "255.255.255.254",
                "255.255.255.252",
                "255.255.255.248",
                "255.255.255.240",
                "255.255.255.224",
                "255.255.255.192",
                "255.255.255.128",
                "255.255.255.0",
                "255.255.254.0",
                "255.255.252.0",
                "255.255.248.0",
                "255.255.240.0",
                "255.255.224.0",
                "255.255.192.0",
                "255.255.128.0",
                "255.255.0.0",
                "255.254.0.0",
                "255.252.0.0",
                "255.248.0.0",
                "255.240.0.0",
                "255.224.0.0",
                "255.192.0.0",
                "255.128.0.0",
                "255.0.0.0",
                "254.0.0.0",
                "252.0.0.0",
                "248.0.0.0",
                "240.0.0.0",
                "224.0.0.0",
                "192.0.0.0",
                "128.0.0.0",
                "0.0.0.0"
            ],
            "[HexChar]": [
                "A",
                "B",
                "C",
                "D",
                "E",
                "F",
                "0",
                "1",
                "2",
                "3",
                "4",
                "5",
                "6",
                "7",
                "8",
                "9"
            ],
            "[Year]": [
                "202[SmallNumber]",
                "201[SmallNumber]",
                "200[SmallNumber]",
                "199[SmallNumber]",
                "198[SmallNumber]",
                "197[SmallNumber]"
            ],
            "[Month]": [
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12"
            ],
            "[Day]": [
                "00",
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31"
            ],
            "[Hour]": [
                "00",
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24"
            ],
            "[Minute]": [
                "00",
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "49",
                "50",
                "51",
                "52",
                "53",
                "54",
                "55",
                "56",
                "57",
                "58",
                "59",
                "60"
            ],
            "[Second]": [
                "00",
                "01",
                "02",
                "03",
                "04",
                "05",
                "06",
                "07",
                "08",
                "09",
                "10",
                "11",
                "12",
                "13",
                "14",
                "15",
                "16",
                "17",
                "18",
                "19",
                "20",
                "21",
                "22",
                "23",
                "24",
                "25",
                "26",
                "27",
                "28",
                "29",
                "30",
                "31",
                "32",
                "33",
                "34",
                "35",
                "36",
                "37",
                "38",
                "39",
                "40",
                "41",
                "42",
                "43",
                "44",
                "45",
                "46",
                "47",
                "48",
                "49",
                "50",
                "51",
                "52",
                "53",
                "54",
                "55",
                "56",
                "57",
                "58",
                "59",
                "60"
            ],
            "[MonthText]": [
                "JAN",
                "FEB",
                "MAR",
                "APR",
                "MAY",
                "JUN",
                "JUL",
                "AUG",
                "SEP",
                "OCT",
                "NOV",
                "DEC"
            ],
            "[DayShort]": [
                "Sun",
                "Mon",
                "Tue",
                "Wed",
                "Thu",
                "Fri",
                "Sat"
            ],
            "[YearShort]": [
                "2[SmallNumber]",
                "1[SmallNumber]",
                "0[SmallNumber]",
                "9[SmallNumber]",
                "8[SmallNumber]",
                "7[SmallNumber]"
            ],
           "[WebServer]": [
               "10.100.116.150"
           ],
           "[WebExecutable]": [
               "[WebServer]/downloads/script.sh",
               "[WebServer]/downloads/script.py",
               "[WebServer]/exec1.sh",
               "[WebServer]/exec2.sh"
           ],
           "[WebPath]": [
               "",
               "/",
               "/exec1.sh",
               "/exec2.sh"
               "/sitemap.xml",
               "/TEST_CASES.md",
               "/home",
               "/page2.html",
               "/redirects/redirect-target.html",
               "/redirects/redirect-source.html",
               "/protected/README.txt",
               "/protected/.htaccess",
               "/robots.txt",
               "/api/v2/users.json",
               "/api/v1/users.json",
               "/data/xml/config.xml",
               "/data/csv/data.csv",
               "/data/json/sample.json",
               "/data/json/large-array.json",
               "/downloads/script.js",
               "/downloads/archives/archive.tar.gz",
               "/downloads/archives/archive.zip",
               "/downloads/script.sh",
               "/downloads/binaries/random.bin",
               "/downloads/binaries/zeros.bin",
               "/downloads/document.md",
               "/downloads/multiline.txt",
               "/downloads/script.py",
               "/downloads/source.c",
               "/downloads/simple.txt",
               "/index.html",
               "/nested/level1/shallow-file.txt",
               "/nested/level1/level2/level3/deep-file.txt",
               "/nested/level1/level2/mid-file.txt"
           ],
           "[URLPrefix]": [
               "http://",
               "https://",
               ""
           ],
           "[URL]": [
               "[URLPrefix]www.[Domain]",
               "www.[Domain]",
               "[Domain]",
               "[IP]",
               "[WebFile]"
           ],
            "[WebFile]": [
                    "[WebServer][WebPath]"
                ],
                "[AnyFile]": [
                    "[File]",
                    "[GlobalFile]",
                    "[WebFile]"
                ],
            "[Extension]": [
                    ".py",
                    ".bak",
                    ".log",
                    ".sh"
                    ".[SmallNumber]",
                    ".gz",
                    ".tar",
                    ".zip",
                    ".img",
                    ".qcow2",
                    ".[Character]"
                ],

                "[HTTPCode]": [
                    "100",
                    "101",
                    "102",
                    "103",
                    "200",
                    "201",
                    "202",
                    "203",
                    "204",
                    "205",
                    "206",
                    "207",
                    "208",
                    "226",
                    "300",
                    "301",
                    "302",
                    "303",
                    "304",
                    "305",
                    "306",
                    "307",
                    "308",
                    "400",
                    "401",
                    "402",
                    "403",
                    "404",
                    "405",
                    "406",
                    "407",
                    "408",
                    "409",
                    "410",
                    "411",
                    "412",
                    "413",
                    "414",
                    "415",
                    "416",
                    "417",
                    "418",
                    "421",
                    "422",
                    "423",
                    "424",
                    "425",
                    "426",
                    "428",
                    "429",
                    "431",
                    "451",
                    "500",
                    "501",
                    "502",
                    "503",
                    "504",
                    "505",
                    "506",
                    "507",
                    "508",
                    "510",
                    "511"
                ],

                "[HTTPContentType]": [
                    "application/json",
                    "application/ld+json",
                    "application/msword",
                    "application/pdf",
                    "application/sql",
                    "application/vnd.api+json",
                    "application/vnd.microsoft.portable-executable",
                    "application/vnd.ms-excel",
                    "application/vnd.ms-powerpoint",
                    "application/vnd.oasis.opendocument.text",
                    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                    "application/x-www-form-urlencoded",
                    "application/xml",
                    "application/zip",
                    "application/zstd",
                    "audio/mpeg",
                    "audio/ogg",
                    "image/avif",
                    "image/jpeg",
                    "image/png",
                    "image/svg+xml",
                    "image/tiff",
                    "model/obj",
                    "multipart/form-data",
                    "text/plain",
                    "text/css",
                    "text/csv",
                    "text/html",
                    "text/javascript",
                    "text/xml"
                ],
               "[IPAddrResolved]": [
                        "[IP]",
                        "[Domain]",
                        "www.[Domain]"
                    ],
               "[RandomString]": [''.join(random.choice(string.ascii_letters + string.digits) for _ in range(random.randint(4, 16))) for __ in range(500)],
               "[Character]": [_ for _ in string.ascii_letters + string.digits]
                           }
RANDOM_NUM_PLACEHOLDERS = {"[Number]": [0, 999],
                           "[SmallNumber]": [1, 9],
                           "[MediumNumber]": [10, 99],
                           "[LargeNumber]": [100, 999],
                           "[LargerNumber]":[999, 9999],
                           "[LargeLargeNumber]": [999, 99999],
                           "[PortNumber]": [1, 1024],
                           "[IPNumber]": [0, 255],
                           "[SubMask]": [0, 32],
                           "[ThirtyTwoBit]": [0, 31]
                           }
MAX_PH_EXEC_TRIES = 5

UNLEARNED_PLACEHOLDERS = LOCAL_RANDOM_PLACEHOLDERS + RANDOM_PLACEHOLDERS + list(RANDOM_NUM_PLACEHOLDERS.keys()) + list(RANDOM_NUM_PLACEHOLDERS.keys())
